plugins { id 'com.android.application' }

android {
    namespace 'observer.noisetriangle'
    compileSdk 35

    defaultConfig {
        applicationId 'observer.noisetriangle'
        minSdk 26
        targetSdk 34
        versionCode 24
        versionName '1.14'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
